### ISSUE TITLE
默认二维码太大了

### ISSUE THREAD

**Issue by cypggs** [0neSe7en/jikefm#4]
![image](https://user-images.githubusercontent.com/3694954/54661191-2f822c00-4b14-11e9-9293-b22ea3882788.png)

**Comment by 0neSe7en** [comment]
恩... 这是个问题。但没太想好处理方式- -、 因为这个二维码的的宽高比较大，而一个像素就对应终端的一个 行/列 。或者也可以生成一个图片，然后打开图片扫描

**Comment by Mogeko** [comment]
可以生成图片保存到桌面上🤔

**Comment by 0neSe7en** [comment]
> 可以生成图片保存到桌面上🤔

可以，不过这样有点点影响用户吧，毕竟在桌面上创建了图片文件。理想情况可以是在临时目录生成图片，调起 **预览.app**，登录成功后关闭 **预览** 并清理没用的图片

**Comment by Mogeko** [comment]
> > 可以生成图片保存到桌面上thinking
> 
> 可以，不过这样有点点影响用户吧，毕竟在桌面上创建了图片文件。理想情况可以是在临时目录生成图片，调起 **预览.app**，登录成功后关闭 **预览** 并清理没用的图片

这样确实比较方便，但如果要适配Windows的话可能会比较麻烦？

可以设置一个时间，比如一分钟之后删除之类的

**Comment by 0neSe7en** [comment]
> 这样确实比较方便，但如果要适配Windows的话可能会比较麻烦？

啊，，，我还没考虑Windows... 手边没有设备- - 😂 似乎确实会有些麻烦。

> 可以设置一个时间，比如一分钟之后删除之类的

这个可以。我找时间研究下Windows平台... (我都没在Windows上尝试编译...

**Comment by Mogeko** [comment]
> > 这样确实比较方便，但如果要适配Windows的话可能会比较麻烦？
> 
> 啊，，，我还没考虑Windows... 手边没有设备- -  似乎确实会有些麻烦。
> 
> > 可以设置一个时间，比如一分钟之后删除之类的
> 
> 这个可以。我找时间研究下Windows平台... (我都没在Windows上尝试编译...

恩恩，昨天看见了 #3，准备自己尝试一下在Windows环境中编译，结果卡在了下载依赖的那一步，因为 golang.org 被墙了。不知道大佬是怎么解决的（本人正在学习go😂😂

**Comment by 0neSe7en** [comment]
> 结果卡在了下载依赖的那一步，因为 golang.org 被墙了。不知道大佬是怎么解决的（本人正在学习go😂😂
我直接路由器翻墙了....没注意这个问题...
似乎只能通过代理吧.. 刚刚查了一下，Go的依赖下载，也没什么好的mirror方案...

**Comment by sdir** [comment]
![image](https://user-images.githubusercontent.com/13232593/55041865-001a7480-506a-11e9-9355-24930dc0015e.png)
这个大小可以吗

**Comment by 0neSe7en** [comment]
@sdir 看起来很不错啊:+1:
